Summary: Build chain of newer git snapshots via rpm specfiles
Name: rpmdistro-gitoverlay
Version: 2015.1
Release: 1%{?dist}
#VCS: https://github.com/cgwalters/rpmdistro-gitoverlay
# This is generated by a recursive "git archive".
Source0: %{name}-%{version}.tar.xz
License: LGPLv2+
URL: https://github.com/cgwalters/rpmdistro-gitoverlay
# We always run autogen.sh
BuildRequires: autoconf automake libtool
BuildRequires: git

Requires: python
Requires: pygobject2
Requires: PyYAML
Requires: pygobject3
Requires: libgsystem
Requires: python-six
Requires: mock
Requires: yum-plugin-priorities

%description
%{summary}

%prep
%autosetup -Sgit

%build
env NOCONFIGURE=1 ./autogen.sh
%configure --disable-silent-rules
make %{?_smp_mflags}

%install
make install DESTDIR=%{buildroot} INSTALL="install -p -c"

%files
%license COPYING
%doc README.md
%{_bindir}/%{name}
%{_libdir}/%{name}/
