#!/usr/bin/env python
#
# Copyright (C) 2015 Colin Walters <walters@verbum.org>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import os
import json
import yaml
import tempfile
import copy

from .swappeddir import SwappedDirectory
from .utils import log, fatal, rmrf, ensure_clean_dir, run_sync
from .task import Task
from . import specfile 
from .git import GitMirror

def require_key(conf, key):
    try:
        return conf[key]
    except KeyError, e:
        fatal("Missing config key {0}".format(key))

class TaskSRPMs(Task):

    def _generate_srpm(self, component, upstream_desc, upstream_co, distgit_co, tmpdir):
        tar_dirname = '{0}-{1}'.format(component['name'], upstream_desc)
        tarname = tar_dirname + '.tar.gz'
        tmp_tarpath = distgit_co + '/' + tarname
        run_sync(['tar', '-czf', tmp_tarpath, '--transform', '^\\./', tar_dirname + '/', upstream_co])
        spec_fn = specfile.spec_fn(distgit_co)
        spec = specfile.Spec(spec_fn)
        spec.set_tag('Source0', tarname)
        spec._txt = '# NOTE: AUTO-GENERATED by rpmdistro-gitoverlay; DO NOT EDIT\n' + spec._txt
        rpmbuild_argv = ['rpmbuild']
        for v in ['_sourcedir', '_specdir', '_builddir',
                  '_srcrpmdir', '_rpmdir']:
            rpmbuild_argv.extend(['--define', v, distgit_co])
        rpmbuild_argv.extend(['-bs', spec_fn])
        run_sync(rpmbuild_argv, cwd=distgit_co)
        srpms = []
        for fname in os.listdir(distgit_co):
            if fname.endswith('.src.rpm'):
                srpms.append(fname)
        if len(srpms) == 0:
            fatal("No .src.rpm found in {0}".format(distgit_co))
        elif len(srpms) > 1:
            fatal("Multiple .src.rpm found in {0}".format(distgit_co))
        srpm = srpms[0]
        os.link(distgit_co + '/' + srpm, self.newsrpms + '/' + srpm)

    def _ensure_srpm(self, component):
        upstream_src = component['src']
        upstream_rev = component['revision']
        [upstream_tag, upstream_rev] = self.mirror.describe(upstream_src, upstream_rev)
        upstream_desc = upstream_rev
        if upstream_tag is not None:
            upstream_desc = upstream_tag + '-' + upstream_desc
        distgit = component['distgit']
        distgit_src = distgit['src']
        distgit_rev = distgit['revision']
        [distgit_tag, distgit_rev] = self.mirror.describe(distgit_src, distgit_rev)
        distgit_desc = distgit_rev
        if distgit_tag is not None:
            distgit_desc = distgit_tag + '-' + distgit_desc

        name = "{0}-{1}-{2}.src.rpm".format(distgit['name'],
                                            upstream_desc, distgit_desc)
        oldpath = self.srpmdir + '/' + name
        if os.path.exists(oldpath):
            log("Reusing cached SRPM: " + name)
            os.link(oldpath, self.newsrpms + '/' + name)
        else:
            tmpdir = tempfile.mkdtemp('', 'rdgo-srpms')
            try:
                upstream_co = tmpdir + '/' + component['name']
                self.mirror.checkout(upstream_src, upstream_rev, upstream_co)
                distgit_co = tmpdir + '/' + distgit['name']
                self.mirror.checkout(distgit_src, distgit_rev, distgit_co)

                self._generate_srpm(component, upstream_desc, upstream_co, distgit_co, tmpdir)
            finally:
                rmrf(tmpdir)

    def run(self):
        snapshot = self.get_snapshot()

        self.srpmdir = SwappedDirectory(self.workdir + '/srpms')
        self.mirror = GitMirror(self.workdir + '/src')
        self.newsrpms = self.srpmdir.prepare()

        for component in snapshot:
            self._ensure_srpm(component)

        self.srpmdir.commit() 
            
